#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Check config file
if [ ! -f  "/config/config.js" ]; then
    cp /opt/config.js /config/config.js
fi

# Check safeloader file
if [ ! -f  "/config/safeloader.sh" ]; then
    cp /opt/safeloader.sh ./safeloader.sh
    chmod +x safeloader.sh
fi
# Check config file
if [ ! -f  "/config/config.sh" ]; then
    cp /opt/config.sh /config/config.sh
fi

# Recompile yencoder
if [ ! -f  "/root/compiled" ]; then
    touch /root/compiled
    cd /usr/src/Nyuu/node_modules/yencode && \
    node-gyp rebuild
fi
